import os
from dotenv import load_dotenv
load_dotenv()

role_admin = int(os.environ["role_admin"])
role_president = int(os.environ["role_president"])
role_executive_officer = int(os.environ["role_executive_officer"])
role_officer = int(os.environ["role_officer"])
role_events = int(os.environ["role_events"])
role_bots = int(os.environ["role_bots"])
role_bot_developers = int(os.environ["role_bot_developers"])
role_faculty = int(os.environ["role_faculty"])
role_alumni = int(os.environ["role_alumni"])
role_security_plus = int(os.environ["role_security_plus"])
role_sfs_scholar = int(os.environ["role_sfs_scholar"])
role_cybersec = int(os.environ["role_cybersec"])
role_cyberops = int(os.environ["role_cyberops"])
role_cybercrime = int(os.environ["role_cybercrime"])
role_engineer = int(os.environ["role_engineer"])
role_compsci = int(os.environ["role_compsci"])
role_blueteam = int(os.environ["role_blueteam"])
role_redteam = int(os.environ["role_redteam"])
role_n2h_blue = int(os.environ["role_n2h_blue"])
role_n2h_red = int(os.environ["role_n2h_red"])
role_n2h_homenet = int(os.environ["role_n2h_homenet"])
role_n2h_certify = int(os.environ["role_n2h_certify"])
role_n2h_code = int(os.environ["role_n2h_code"])